### ISSUE TITLE
rar2fs not working on docker

### ISSUE THREAD

**Issue by swordh** [Pretagonist/plex-rar2fs-docker#2]
When starting the container the rar2fs isn't available.

```
plex          | [cont-init.d] executing container initialization scripts...
plex          | [cont-init.d] 30-rar2fs-mount: executing...
plex          | /var/run/s6/etc/cont-init.d/30-rar2fs-mount: line 27: rar2fs: command not found
```
however, if I clone the repository and build it myself, without changes, it works as expected

**Comment by Pretagonist** [comment]
I've been having strange issues with this myself but I thought I fixed it. Will take a look.

**Comment by Pretagonist** [comment]
I had fixed it, just not on the public branch. It's fixed now and docker hub is building a new release.

**Comment by swordh** [comment]
Thx man! How long will it take until it is available for download? The last update is 19 days ago.

**Comment by Pretagonist** [comment]
Yeah, seems that my autobuild stuff got deleted or something. Hopefully it'll start working soon. Sorry about that.

**Comment by Pretagonist** [comment]
So, build is up on docker hub. Thanks for bringing this to my attention.
